variable "location" {}
variable "resource_group_name" {}
variable "vm_name" {}
variable "vm_size" {}
variable "ssh_key_public" {}
variable "subnet_id" {}
variable "public_ip_id" {}
variable "public_ip_address" {}
variable "storage_account_name" {}
variable "storage_container" {}
variable "storage_account_primary_blob_endpoint" {}