variable "location" {}
variable "resource_group_name" {}
variable "virtual_network_name" {}
variable "vnet_address_prefix" {}
variable "subnet_name" {}
variable "subnet_address_prefix" {}
variable "network_security_group_name" {}
variable "public_ip_address_name" {}
variable "dns_label" {}